import ENV_VARS from "../../tools/ENV_VARS";

console.log(ENV_VARS)
export default {
    GOOGLE_CLOUD_API_KEY: ENV_VARS.API_KEYS.GOOGLE_CLOUD_API_KEY,
    GOOGLE_NL_API_URL: "https://language.googleapis.com/v1beta1/documents:analyzeEntities?key=",
    NL_INIT: 'NL_INIT',
    NL_SUCCESS: 'NL_SUCCESS',
    NL_ERROR: 'NL_ERROR',
    LUIS_SUBSCRIPTION_KEY: ENV_VARS.API_KEYS.LUIS_SUBSCRIPTION_KEY,
    LUIS_APPLICATION_ID: ENV_VARS.API_KEYS.LUIS_APPLICATION_ID,
    LUIS_SUBSCRIPTION_KEY_2: ENV_VARS.API_KEYS.LUIS_SUBSCRIPTION_KEY_2,
    LUIS_APPLICATION_ID_2: ENV_VARS.API_KEYS.LUIS_APPLICATION_ID_2,
}