export default {
    EDIT_TITLE: 'EDIT_TITLE',
    INIT_EDIT_TITLE: 'INIT_EDIT_TITLE',
    INIT_EDIT_COLOR: 'INIT_EDIT_COLOR',
    EDIT_DESCRIPTION: 'EDIT_DESCRIPTION',
    SET_ARTICLES: 'SET_ARTICLES',
    CHANGE_COLOR: "TEXT_COLOR",
    RESET: "RESET"
}
